- name: Download Europe extract
  get_url:
    url: "{{ osm_url }}"
    dest: /tmp/openstreetmap-latest.osm.pbf
    timeout: 600

- name: Get poly file for Belgium
  get_url:
    url: "{{ poly_url }}"
    dest: /tmp/extract.poly

- name: Create Belgium extract
  shell: |
    osmium extract \
      --strategy smart \
      --polygon=/tmp/extract.poly \
      --output=/tmp/openstreetmap-latest-extract.osm.pbf \
      --overwrite \
      /tmp/openstreetmap-latest.osm.pbf
